Update bitmoeinc.md
cnrv/riscv-innovations pull request #94
Opened 2022-11-26 01:41 UTC by NaopTrump08

2022-11-26 01:42 UTC, NaopTrump08 commented
NaopTrump08

2022-11-26 01:43 UTC, NaopTrump08 commented
添加申请

2022-11-27 06:44 UTC, lazyparser commented
存在冲突，请先rebase

2022-11-27 06:46 UTC, lazyparser requested changes
rebase needed

2022-11-30 08:35 UTC, lazyparser commented
感谢您的参与，欢迎关注CNRV后续活动。

（关闭因为没有及时修改而导致第一次审核未通过的PR。）

看起来原始申请已经merge？如果已经merge，请rebase之后再发起修改，文件位置有可能已经发生了变更。

2022-11-30 08:35 UTC, closed without merging